apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: guy958pdo-go 
  janus-idp.io/tekton: guy958pdo-go
  backstage.io/kubernetes-id: guy958pdo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: guy958pdo-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  