apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: guy958pdo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: guy958pdo-go 
  name: guy958pdo-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: guy958pdo-go 
